export const COLORS = {
  primary: "#C8860A",
  primaryLight: "#E8A830",
  primaryDark: "#8B5E08",
  bg: "#1A1410",
  surface: "#231C15",
  surfaceHover: "#2E2318",
  border: "#3D2E1E",
  text: "#F5ECD7",
  textMuted: "#9A8468",
  textDim: "#6B5A45",
  danger: "#C0392B",
  dangerLight: "#E74C3C",
  success: "#27AE60",
  successLight: "#2ECC71",
  warning: "#E67E22",
  info: "#2980B9",
};

export const icons = {
  dashboard: "⊞",
  users: "👥",
  guides: "🧭",
  places: "🏛",
  trips: "✈",
  bookings: "📋",
  payments: "💳",
  reviews: "⭐",
  nationalities: "🌍",
  roles: "🛡",
  notifications: "🔔",
  menu: "☰",
  close: "✕",
  approve: "✓",
  reject: "✗",
  delete: "🗑",
  view: "👁",
  edit: "✏",
  add: "＋",
  search: "⌕",
  logout: "⎋",
  pending: "⏳",
  active: "●",
  chevron: "›",
};
