/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, useEffect, useMemo, useState } from "react";

const LANGUAGE_STORAGE_KEY = "degy_language";
const RTL_LANGUAGES = new Set(["ar"]);

const TRANSLATIONS = {
  en: {
    meta: {
      title: "Discover Egypt - Travel & Adventure",
      description:
        "Discover Egypt - Travel, enjoy and live a new and full life with authentic Egyptian experiences",
    },
    common: {
      home: "Home",
      explore: "Explore",
      aboutUs: "About Us",
      bookmarks: "Bookmarks",
      login: "Login",
      signup: "Sign up",
      logout: "Log out",
      menu: "Menu",
      searchPrompt: "What's on your mind?",
      search: "Search",
      switchToArabic: "Switch to Arabic",
      switchToEnglish: "Switch to English",
      english: "EN",
      arabic: "AR",
      close: "Close",
      welcomeBack: "Welcome back",
      loading: "Loading...",
      selectLanguage: "Select language",
      cancel: "Cancel",
      points: "Points",
      notifications: "Notifications",
    },
    tourist: {
      home: {
        description: "Manage incoming requests, conversations, and trip updates from one place.",
        noUpcomingTrips: "No upcoming trips.",
      },
    },
    hero: {
      badge: "Best Destinations Around Egypt",
      title: "Travel, enjoy and live a new and full life",
      description:
        "Worem ipsum dolor sit amet, consectetur adipiscing elit. Worem ipsum dolor sit amet, consectetur adipiscing elit. Worem ipsum dolor sit amet,",
      cta: "Find out more",
      playDemo: "Play demo video",
      downloadNow: "Download Now!",
      alt: "Happy traveller with suitcase exploring Egypt",
    },
    about: {
      title: "About Us",
      downloads: "Total Downloads",
      ratings: "App Ratings",
      outOf: "out of 5",
      ratingsBadge: "32 Ratings",
      conversionRate: "Conversion Rate",
    },
    features: {
      title: "Our Features",
      items: [
        {
          title: "Exclusive Designs",
          description:
            "We work closely with talented ceramic artists to bring you exclusive and one-of-a-kind designs.",
          link: "Learn more",
        },
        {
          title: "Exclusive Designs",
          description:
            "We work closely with talented ceramic artists to bring you exclusive and one-of-a-kind designs.",
          link: "Learn more",
        },
        {
          title: "Exclusive Designs",
          description:
            "We work closely with talented ceramic artists to bring you exclusive and one-of-a-kind designs.",
          link: "Learn more",
        },
      ],
    },
    footer: {
      brandName: "Discover Egypt",
      brandDescription:
        "We bring authentic Egyptian experiences to the world with culture, history, and adventure.",
      usefulLinks: "Useful Links",
      resources: "Resources",
      becomeGuide: "Become a guide",
      support: "Support",
      help: "Help",
      contactUs: "Contact Us",
      copyright: "©2025 DiscoverEgypt",
    },
    auth: {
      loginTitle: "Login now",
      loginSubtitle: "Please sign in to continue our app",
      createAccountTitle: "Create Account",
      createAccountSubtitle: "Fill in your details to get started",
      tourist: "Tourist",
      guide: "Guide",
      firstNamePlaceholder: "First name",
      lastNamePlaceholder: "Last name",
      firstNameRequired: "First name is required",
      lastNameRequired: "Last name is required",
      emailAddress: "Email address",
      phoneNumber: "Phone number",
      phonePlaceholder: "01xxxxxxxxx",
      gender: "Gender",
      dobPlaceholder: "Date of Birth",
      dobRequired: "Date of Birth is required",
      password: "Password",
      confirmPassword: "Confirm password",
      selectGender: "Gender",
      selectNationality: "Select nationality",
      selectLanguages: "Select languages you speak",
      licenseIdPlaceholder: "License ID",
      licenseIdRequired: "License ID is required",
      uploadLicenseImage: "Upload license image",
      licenseImageRequired: "License image is required",
      noAccount: "Don't have an account?",
      alreadyHaveAccount: "Already have an account?",
      signIn: "Sign in",
      signUp: "Sign up",
      forgotPassword: "Forgot Password?",
      loginButton: "Login",
      loginLoading: "Logging in...",
      createButton: "Create Account",
      createLoading: "Creating account...",
      orConnect: "Or connect",
      orConnectWith: "Or connect with",
      facebook: "Facebook",
      google: "Google",
      instagram: "Instagram",
      showPassword: "Show password",
      hidePassword: "Hide password",
      invalidEmail: "Invalid email",
      emailRequired: "Email is required",
      passwordMin6: "Min 6 characters",
      passwordRequired: "Password is required",
      loginError: "Invalid email or password",
      emailExists: "Email already exists",
      resetRequestSubtitle: "Enter your email to receive a reset code.",
      resetPasswordSubtitle: "Enter the code sent to {{email}} and your new password.",
      sendResetCode: "Send reset code",
      resetPasswordAction: "Reset password",
      resetCodeSent: "Reset code sent successfully.",
      resetRequestFailed: "Could not send reset code.",
      resetFailed: "Could not reset password.",
      passwordResetSuccess: "Password reset successfully. Redirecting to login...",
      otpPlaceholder: "Reset code (OTP)",
      otpRequired: "Reset code is required",
      newPassword: "New password",
      submitting: "Submitting...",
      profileSettings: "Profile Settings",
      updateProfile: "Update Profile",
      saveChanges: "Save Changes",
      profileUpdated: "Profile updated successfully.",
      profileUpdateFailed: "Could not update profile.",
      changePasswordTitle: "Change Password",
      passwordChanged: "Password changed successfully.",
      passwordChangeFailed: "Could not change password.",
      deleteAccount: "Delete Account",
      deleteAccountHint: "This action is permanent and cannot be undone.",
      deleteAccountConfirm: "Are you sure you want to permanently delete your account?",
      deleteAccountFailed: "Could not delete account.",
      bookingInstructions: "Fill in your details to complete your booking",
      nameRequired: "Name is required",
      phoneInvalid: "Invalid phone number",
      phoneRequired: "Phone number is required",
      genderRequired: "Gender is required",
      confirmRequired: "Confirm your password",
      passwordsMatch: "Passwords must match",
      nationalityRequired: "Nationality is required",
      languagesRequired: "Languages are required",
      selectAtLeastOneLanguage: "Select at least one language",
      nationalityEgyptian: "Egyptian",
      genderMale: "Male",
      genderFemale: "Female",
    },
    search: {
      placeholder: "Search destinations...",
      ariaLabel: "Search destinations",
      noResultsTitle: "No destinations found",
      noResultsHint: 'Try searching for "Luxor", "Cairo", or "Pyramids"',
      resultsFound: "{{count}} destination{{suffix}} found{{query}}",
    },
    bookmarks: {
      title: "My Bookmarks ({{count}})",
      emptyTitle: "No bookmarks yet",
      emptyBody:
        "Start exploring and save your favorite destinations!",
      exploreDestinations: "Explore Destinations",
      removeBookmark: "Remove {{name}} from bookmarks",
    },
    destination: {
      notFound: "Destination not found",
      goBackHome: "Go back home",
      details: "Details",
      description: "Description",
      comments: "Comments",
      reviews: "reviews",
      bookNow: "Book now",
      call: "Call",
      viewLocation: "View location",
      verified: "Verified",
      photos: "Photos",
      currentActivities: "Current Activities",
      popularAttractions: "Popular Attractions",
      upcomingTrips: "Upcoming Trips",
      cancelTrip: "Cancel trip",
      cancelTripFailed: "Could not cancel this trip right now.",
      noPhotos: "No photos available.",
    },
    guide: {
      home: {
        description: "Manage incoming requests, conversations, and trip updates from one place.",
      },
      chats: {
        title: "Chats",
        description: "Continue conversations with tourists about their trips.",
      },
      notifications: {
        title: "Notifications",
        description: "Check new booking, account, and system updates.",
      },
    },
    booking: {
      title: "Book Your Trip",
      confirmedTitle: "Booking Confirmed!",
      confirmPaymentTitle: "Confirm payment",
      confirmPaymentBody: "You are about to pay {{amount}} for this trip.",
      confirmAndPay: "Confirm and pay",
      amountDue: "Amount due",
      confirmedWithAmount: "Booking confirmed. Payment amount: {{amount}}.",
      thankYou: "Thank You!",
      submitted: "Your booking request for {{name}} has been submitted.",
      contactSoon: "We will contact you shortly to confirm your reservation.",
      done: "Done",
      fullName: "Full Name",
      phoneNumber: "Phone Number",
      address: "Address",
      tripDate: "Trip Date",
      paymentMethod: "Payment Method",
      submit: "Submit",
      submitting: "Submitting...",
      namePlaceholder: "Enter your full name",
      phonePlaceholder: "01xxxxxxxxx",
      addressPlaceholder: "Enter your full address",
      selectPayment: "Select a payment method",
      paymentRequired: "Payment method is required",
      bookingInstructions: "Fill in your details to complete your booking",
      paymentOptions: {
        instapay: { name: "InstaPay", description: "Pay via InstaPay" },
        vodafone_cash: {
          name: "Vodafone Cash",
          description: "Pay via Vodafone Cash",
        },
      },
    },
    validation: {
      nameMin2: "Min 2 characters",
      invalidEmail: "Invalid email",
      phoneInvalid: "Invalid phone number",
      required: "This field is required",
      passwordMin6: "Min 6 characters",
      confirmMatch: "Passwords must match",
      ageNumber: "Must be a number",
      ageMin: "Must be at least 16",
      ageMax: "Invalid age",
      addressMin: "Please enter a complete address",
      futureDate: "Date must be in the future",
      paymentMethodRequired: "Payment method is required",
      selectOneLanguage: "Select at least one language",
      selectNationality: "Nationality is required",
      selectPlanFirst: "Please select a plan first!",
      fillAllFields: "Please fill in all booking details (date, duration, and time).",
    },
    requests: {
      title: "Your Requests",
      clearAll: "Clear All",
      accept: "Accept",
      chat: "Chat",
      yourTrips: "Your Accepted Trips",
      noTrips: "No active trips currently",
      checking: "Checking for new requests...",
      touristName: "Tourist Name",
      type: "Type",
      location: "Location",
      date: "Date",
      people: "People",
      accepted: "ACCEPTED",
    },
    chats: {
      title: "Chats",
      clearAll: "Clear All",
      searchPlaceholder: "Search conversations...",
      typeMessage: "Type your message here.....",
      deleteChat: "Delete Chat",
      reportGuide: "Report Tour Guide",
      reportUser: "Report User",
      online: "Online",
      download: "Download",
      noConversations: "No conversations found.",
      errorLoading: "Could not load conversations.",
    },
    notifications: {
      title: "Notifications",
      empty: "No notifications available.",
      selectOne: "Select a notification to view details.",
      refresh: "Refresh",
      delete: "Delete",
      loadFailed: "Could not load notifications.",
      deleteFailed: "Could not delete notification.",
    },
    availableGuides: {
      title: "Available Tour Guides",
      successTitle: "Trip Booked!",
      successBody: "You have successfully booked {{name}}. You can now find this trip in your upcoming list and start chatting!",
      goTrips: "Go to Trips",
      noGuides: "No guides available at the moment.",
      errorLoading: "Could not load available guides.",
      bookingFailed: "Could not complete guide booking.",
    },
    createPlan: {
      title: "Custom Plan",
      placeholder: "Tell AI what you want to visit...",
      generate: "Generate",
      selectTitle: "Select your AI generated plan",
      resultsFor: "Results for \"{{query}}\"",
      emptyState: "Enter a destination above to generate plans using AI",
      dateLabel: "Date :",
      durationLabel: "Duration :",
      startTimeLabel: "Start Time :",
      dayPlaceholder: "day",
      monthPlaceholder: "months",
      yearPlaceholder: "year",
      durationPlaceholder: "e.g. 5 hours",
      startTimePlaceholder: "e.g. 9:00 AM",
      submit: "Submit",
      selectedStops: "Selected Stops",
      addPlace: "Add Place",
      searchPlaceholder: "Search sites, beaches, temples...",
      emptyStops: "No places added yet. Use 'Add Place' to start.",
      noResults: "No places found.",
      tripDetails: "Trip Details",
      editInPay: "Edit booking details",
      missingDetails: "Missing booking details. Set date in Pay, and set start time and duration here.",
      selectTime: "Select time",
      hours: "hours",
      invalidBookingDetails: "Please fill in all booking details (date, duration, and time).",
      planSavedTitle: "Plan saved",
      planSaveFailed: "Plan failed",
      chooseGuideNext: "Custom plan saved. Choose a guide to complete your booking.",
    },
    plans: {
      title: "Plans",
      seeMore: "see more",
      destinationsCount: "destinations",
      recommendedFor: "Recommended Trips For",
      recommendedDesc: "We've matched your selected destination with our best preset plans. Choose one below to start your adventure.",
      noPlansFound: "No plans found.",
      noTripsFoundForDestination: "No trips found for this destination.",
      showOtherTrips: "Show other trips",
      hideOtherTrips: "Hide other trips",
      otherTripsTitle: "Other trips",
      matchingTrips: "Matching trips",
      allTrips: "All trips",
    },
    admin: {
      eyebrow: "Admin",
      title: "Dashboard",
      subtitle: "Live overview of users, guides, places, trips, bookings, and revenue.",
      refresh: "Refresh",
      loadFailed: "Could not load dashboard data.",
      users: "Users",
      guides: "Guides",
      places: "Places",
      readyTrips: "Ready trips",
      customTrips: "Custom trips",
      revenue: "Revenue",
      recentBookings: "Recent bookings",
      pendingGuides: "Pending guides",
      trip: "Trip",
      guide: "Guide",
      amount: "Amount",
      status: "Status",
      unassigned: "Unassigned",
      noBookings: "No bookings found.",
      noPendingGuides: "No pending guides.",
    },
  },
  ar: {
    meta: {
      title: "اكتشف مصر - السفر والمغامرة",
      description:
        "اكتشف مصر - سافر واستمتع وعش حياة جديدة ومتكاملة مع تجارب مصرية أصيلة",
    },
    common: {
      home: "الرئيسية",
      explore: "استكشف",
      aboutUs: "من نحن",
      bookmarks: "المحفوظات",
      login: "تسجيل الدخول",
      signup: "إنشاء حساب",
      logout: "تسجيل الخروج",
      menu: "القائمة",
      searchPrompt: "ما الذي يدور في بالك؟",
      search: "بحث",
      switchToArabic: "التبديل إلى العربية",
      switchToEnglish: "التبديل إلى الإنجليزية",
      english: "EN",
      arabic: "AR",
      close: "إغلاق",
      welcomeBack: "مرحبًا بعودتك",
      loading: "جارٍ التحميل...",
      selectLanguage: "اختر اللغة",
      cancel: "إلغاء",
      points: "النقاط",
      notifications: "الإشعارات",
    },
    hero: {
      badge: "أفضل الوجهات حول مصر",
      title: "سافر واستمتع وعش حياة جديدة ومليئة بالطاقة",
      description:
        "نص تجريبي طويل يصف رحلة مميزة وتجربة ممتعة مع محتوى حقيقي وأجواء سياحية ملهمة.",
      cta: "اعرف المزيد",
      playDemo: "تشغيل الفيديو التجريبي",
      downloadNow: "حمّل الآن!",
      alt: "مسافر سعيد يحمل حقيبة ويستكشف مصر",
    },
    about: {
      title: "من نحن",
      downloads: "إجمالي التنزيلات",
      ratings: "تقييم التطبيق",
      outOf: "من 5",
      ratingsBadge: "32 تقييمًا",
      conversionRate: "معدل التحويل",
    },
    features: {
      title: "مميزاتنا",
      items: [
        {
          title: "تصاميم حصرية",
          description:
            "نعمل عن قرب مع فنانين موهوبين لتقديم تصاميم حصرية وفريدة من نوعها.",
          link: "اعرف المزيد",
        },
        {
          title: "تصاميم حصرية",
          description:
            "نعمل عن قرب مع فنانين موهوبين لتقديم تصاميم حصرية وفريدة من نوعها.",
          link: "اعرف المزيد",
        },
        {
          title: "تصاميم حصرية",
          description:
            "نعمل عن قرب مع فنانين موهوبين لتقديم تصاميم حصرية وفريدة من نوعها.",
          link: "اعرف المزيد",
        },
      ],
    },
    footer: {
      brandName: "اكتشف مصر",
      brandDescription:
        "نقدم التجارب المصرية الأصيلة للعالم من خلال الثقافة والتاريخ والمغامرة.",
      usefulLinks: "روابط مفيدة",
      resources: "الموارد",
      becomeGuide: "كن دليلًا سياحيًا",
      support: "الدعم",
      help: "المساعدة",
      contactUs: "تواصل معنا",
      copyright: "©2025 اكتشف مصر",
    },
    auth: {
      loginTitle: "سجّل الدخول الآن",
      loginSubtitle: "يرجى تسجيل الدخول للمتابعة في التطبيق",
      createAccountTitle: "إنشاء حساب",
      createAccountSubtitle: "أدخل بياناتك للبدء",
      tourist: "سائح",
      guide: "دليل",
      firstNamePlaceholder: "الاسم الأول",
      lastNamePlaceholder: "الاسم الأخير",
      firstNameRequired: "الاسم الأول مطلوب",
      lastNameRequired: "الاسم الأخير مطلوب",
      emailAddress: "البريد الإلكتروني",
      phoneNumber: "رقم الهاتف",
      phonePlaceholder: "01xxxxxxxxx",
      gender: "النوع",
      dobPlaceholder: "تاريخ الميلاد",
      dobRequired: "تاريخ الميلاد مطلوب",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      selectGender: "النوع",
      selectNationality: "اختر الجنسية",
      selectLanguages: "اختر اللغات التي تتحدثها",
      licenseIdPlaceholder: "رقم الترخيص",
      licenseIdRequired: "رقم الترخيص مطلوب",
      uploadLicenseImage: "رفع صورة الترخيص",
      licenseImageRequired: "صورة الترخيص مطلوبة",
      noAccount: "ليس لديك حساب؟",
      alreadyHaveAccount: "لديك حساب بالفعل؟",
      signIn: "تسجيل الدخول",
      signUp: "إنشاء حساب",
      forgotPassword: "هل نسيت كلمة المرور؟",
      loginButton: "تسجيل الدخول",
      loginLoading: "جارٍ تسجيل الدخول...",
      createButton: "إنشاء حساب",
      createLoading: "جارٍ إنشاء الحساب...",
      orConnect: "أو اتصل عبر",
      orConnectWith: "أو اتصل عبر",
      facebook: "فيسبوك",
      google: "جوجل",
      instagram: "إنستغرام",
      showPassword: "إظهار كلمة المرور",
      hidePassword: "إخفاء كلمة المرور",
      invalidEmail: "البريد الإلكتروني غير صحيح",
      emailRequired: "البريد الإلكتروني مطلوب",
      passwordMin6: "6 أحرف على الأقل",
      passwordRequired: "كلمة المرور مطلوبة",
      loginError: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
      emailExists: "البريد الإلكتروني موجود بالفعل",
      resetRequestSubtitle: "أدخل بريدك الإلكتروني لاستلام رمز إعادة التعيين.",
      resetPasswordSubtitle: "أدخل الرمز المُرسل إلى {{email}} وكلمة المرور الجديدة.",
      sendResetCode: "إرسال رمز إعادة التعيين",
      resetPasswordAction: "إعادة تعيين كلمة المرور",
      resetCodeSent: "تم إرسال رمز إعادة التعيين بنجاح.",
      resetRequestFailed: "تعذر إرسال رمز إعادة التعيين.",
      resetFailed: "تعذر إعادة تعيين كلمة المرور.",
      passwordResetSuccess: "تمت إعادة تعيين كلمة المرور بنجاح. جارٍ التحويل لتسجيل الدخول...",
      otpPlaceholder: "رمز إعادة التعيين (OTP)",
      otpRequired: "رمز إعادة التعيين مطلوب",
      newPassword: "كلمة مرور جديدة",
      submitting: "جارٍ الإرسال...",
      profileSettings: "إعدادات الحساب",
      updateProfile: "تحديث الملف الشخصي",
      saveChanges: "حفظ التغييرات",
      profileUpdated: "تم تحديث الملف الشخصي بنجاح.",
      profileUpdateFailed: "تعذر تحديث الملف الشخصي.",
      changePasswordTitle: "تغيير كلمة المرور",
      passwordChanged: "تم تغيير كلمة المرور بنجاح.",
      passwordChangeFailed: "تعذر تغيير كلمة المرور.",
      deleteAccount: "حذف الحساب",
      deleteAccountHint: "هذا الإجراء دائم ولا يمكن التراجع عنه.",
      deleteAccountConfirm: "هل أنت متأكد من حذف حسابك نهائيًا؟",
      deleteAccountFailed: "تعذر حذف الحساب.",
      nameRequired: "الاسم مطلوب",
      phoneInvalid: "رقم الهاتف غير صحيح",
      phoneRequired: "رقم الهاتف مطلوب",
      genderRequired: "النوع مطلوب",
      confirmRequired: "يرجى تأكيد كلمة المرور",
      passwordsMatch: "كلمتا المرور غير متطابقتين",
      nationalityRequired: "الجنسية مطلوبة",
      languagesRequired: "اللغات مطلوبة",
      selectAtLeastOneLanguage: "اختر لغة واحدة على الأقل",
      nationalityEgyptian: "مصري",
      genderMale: "ذكر",
      genderFemale: "أنثى",
    },
    guide: {
      home: {
        description: "قم بإدارة الطلبات الواردة، المحادثات، وتحديثات الرحلات من مكان واحد.",},
      chats: {
        title: "المحادثات",
        description: "متابعة المحادثات مع السياح حول رحلاتهم.",
      },
      notifications: {
        title: "الإشعارات",
        description: "تحقق من الحجوزات الجديدة، والحساب، والتحديثات النظامية.",
      },
    },
    tourist: {
      home: {
        description: "قم بإدارة الطلبات الواردة، المحادثات، وتحديثات الرحلات من مكان واحد.",
        noUpcomingTrips: "لا توجد رحلات قادمة.",
      },
    },
    booking: {
      title: "احجز رحلتك",
      confirmedTitle: "تم تأكيد الحجز!",
      confirmPaymentTitle: "تأكيد الدفع",
      confirmPaymentBody: "أنت على وشك دفع {{amount}} لهذه الرحلة.",
      confirmAndPay: "تأكيد ودفع",
      amountDue: "المبلغ المطلوب",
      confirmedWithAmount: "تم تأكيد الحجز. مبلغ الدفع: {{amount}}.",
      thankYou: "شكرًا لك!",
      submitted: "تم إرسال طلب الحجز لـ {{name}}.",
      contactSoon: "سنتواصل معك قريبًا لتأكيد الحجز.",
      done: "تم",
      fullName: "الاسم الكامل",
      phoneNumber: "رقم الهاتف",
      address: "العنوان",
      tripDate: "تاريخ الرحلة",
      paymentMethod: "طريقة الدفع",
      submit: "إرسال",
      submitting: "جارٍ الإرسال...",
      namePlaceholder: "أدخل اسمك الكامل",
      phonePlaceholder: "01xxxxxxxxx",
      addressPlaceholder: "أدخل عنوانك الكامل",
      selectPayment: "اختر طريقة الدفع",
      paymentRequired: "طريقة الدفع مطلوبة",
      bookingInstructions: "أدخل بياناتك لإكمال عملية الحجز",
      paymentOptions: {
        instapay: { name: "إنستا باي", description: "ادفع عبر إنستا باي" },
        vodafone_cash: {
          name: "فودافون كاش",
          description: "ادفع عبر فودافون كاش",
        },
      },
    },
    validation: {
      nameMin2: "حرفان على الأقل",
      invalidEmail: "البريد الإلكتروني غير صحيح",
      phoneInvalid: "رقم الهاتف غير صحيح",
      required: "هذه الخانة مطلوبة",
      passwordMin6: "6 أحرف على الأقل",
      confirmMatch: "كلمتا المرور غير متطابقتين",
      ageNumber: "يجب أن يكون رقمًا",
      ageMin: "يجب ألا يقل العمر عن 16",
      ageMax: "العمر غير صالح",
      addressMin: "يرجى إدخال عنوان كامل",
      futureDate: "يجب أن يكون التاريخ في المستقبل",
      paymentMethodRequired: "طريقة الدفع مطلوبة",
      selectOneLanguage: "اختر لغة واحدة على الأقل",
      selectNationality: "الجنسية مطلوبة",
      selectPlanFirst: "يرجى اختيار خطة أولاً!",
      fillAllFields: "يرجى ملء جميع تفاصيل الحجز (التاريخ، المدة، والوقت).",
    },
    bookmarks: {
      title: "محفوظاتي ({{count}})",
      emptyTitle: "لا توجد محفوظات حتى الآن",
      emptyBody: "ابدأ الاستكشاف واحفظ وجهاتك المفضلة!",
      exploreDestinations: "استكشف الوجهات",
      removeBookmark: "إزالة {{name}} من المحفوظات",
    },
    destination: {
      notFound: "الوجهة غير موجودة",
      goBackHome: "العودة للرئيسية",
      details: "التفاصيل",
      description: "الوصف",
      comments: "التعليقات",
      reviews: "تقييمات",
      bookNow: "احجز الآن",
      call: "اتصال",
      viewLocation: "عرض الموقع",
      verified: "موثّق",
      photos: "صور",
      currentActivities: "الأنشطة الحالية",
      popularAttractions: "مناطق الجذب الشهيرة",
      upcomingTrips: "رحلات قادمة",
      cancelTrip: "إلغاء الرحلة",
      cancelTripFailed: "تعذّر إلغاء هذه الرحلة الآن.",
      noPhotos: "لا توجد صور متاحة.",
    },
    requests: {
      title: "طلباتك",
      clearAll: "مسح الكل",
      accept: "قبول",
      chat: "محادثة",
      yourTrips: "رحلاتك المقبولة",
      noTrips: "لا توجد رحلات نشطة حالياً",
      checking: "جارٍ التحقق من وجود طلبات جديدة...",
      touristName: "اسم السائح",
      type: "النوع",
      location: "الموقع",
      date: "التاريخ",
      people: "الأفراد",
      accepted: "مقبول",
      errorLoading: "حدث خطأ أثناء تحميل الطلبات.",
      noRequests: "لا توجد طلبات جديدة في الوقت الحالي.",
    },
    chats: {
      title: "المحادثات",
      clearAll: "مسح الكل",
      searchPlaceholder: "البحث في المحادثات...",
      typeMessage: "اكتب رسالتك هنا.....",
      deleteChat: "حذف المحادثة",
      reportGuide: "الإبلاغ عن المرشد",
      reportUser: "الإبلاغ عن المستخدم",
      online: "متصل",
      download: "تنزيل",
      noConversations: "لا توجد محادثات.",
      errorLoading: "حدث خطأ أثناء تحميل المحادثات.",
    },
    notifications: {
      title: "الإشعارات",
      empty: "لا توجد إشعارات حالياً.",
      selectOne: "اختر إشعارًا لعرض التفاصيل.",
      refresh: "تحديث",
      delete: "حذف",
      loadFailed: "تعذر تحميل الإشعارات.",
      deleteFailed: "تعذر حذف الإشعار.",
    },
    availableGuides: {
      title: "المرشدين المتاحين",
      successTitle: "تم الحجز بنجاح!",
      successBody: "لقد قمت بحجز {{name}} بنجاح. يمكنك الآن العثور على هذه الرحلة في قائمة رحلاتك القادمة وبدء الدردشة!",
      goTrips: "الذهاب إلى الرحلات",
      noGuides: "لا يوجد مرشدين متاحين في الوقت الحالي.",
      errorLoading: "تعذر تحميل المرشدين المتاحين.",
      bookingFailed: "تعذر إكمال حجز المرشد.",
    },
    createPlan: {
      title: "خطة مخصصة",
      placeholder: "أخبر الذكاء الاصطناعي عما تريد زيارته...",
      generate: "إنشاء",
      selectTitle: "اختر خطتك المنشأة بالذكاء الاصطناعي",
      resultsFor: "نتائج البحث عن \"{{query}}\"",
      emptyState: "أدخل وجهة أعلاه ليقوم الذكاء الاصطناعي برسم الخطة لك",
      dateLabel: "التاريخ :",
      durationLabel: "المدة :",
      startTimeLabel: "وقت البدء :",
      dayPlaceholder: "يوم",
      monthPlaceholder: "شهر",
      yearPlaceholder: "سنة",
      durationPlaceholder: "مثل: 5 ساعات",
      startTimePlaceholder: "مثل: 9:00 صباحاً",
      submit: "تأكيد",
      selectedStops: "المحطات المختارة",
      addPlace: "إضافة مكان",
      searchPlaceholder: "ابحث عن المواقع التاريخية، الشواطئ، المعابد...",
      emptyStops: "لم يتم إضافة أماكن بعد. استخدم 'إضافة مكان' للبدء.",
      noResults: "لم يتم العثور على أماكن.",
      tripDetails: "تفاصيل الرحلة",
      editInPay: "تعديل تفاصيل الحجز",
      missingDetails: "تفاصيل الحجز مفقودة. قم بتحديد التاريخ في الدفع، وحدد وقت البدء والمدة هنا.",
      selectTime: "اختر الوقت",
      hours: "ساعات",
      invalidBookingDetails: "يرجى ملء جميع تفاصيل الحجز (التاريخ، المدة، والوقت).",
      planSavedTitle: "تم حفظ الخطة",
      planSaveFailed: "فشل حفظ الخطة",
      chooseGuideNext: "تم حفظ الخطة المخصصة. اختر مرشدًا لإكمال الحجز.",
    },
    plans: {
      title: "الخطط",
      seeMore: "اعرف المزيد",
      destinationsCount: "وجهة",
      recommendedFor: "رحلات مقترحة لـ",
      recommendedDesc: "لقد قمنا بمطابقة وجهتك المختارة مع أفضل خططنا الجاهزة. اختر إحداها أدناه لبدء مغامرتك.",
      noPlansFound: "لم يتم العثور على خطط.",
      noTripsFoundForDestination: "لم يتم العثور على رحلات لهذه الوجهة.",
      showOtherTrips: "عرض رحلات أخرى",
      hideOtherTrips: "إخفاء الرحلات الأخرى",
      otherTripsTitle: "رحلات أخرى",
      matchingTrips: "الرحلات المتطابقة",
      allTrips: "جميع الرحلات",
    },
    admin: {
      eyebrow: "المدير",
      title: "لوحة التحكم",
      subtitle: "نظرة مباشرة على المستخدمين، المرشدين، الأماكن، الرحلات، الحجوزات، والإيرادات.",
      refresh: "تحديث",
      loadFailed: "تعذر تحميل بيانات لوحة التحكم.",
      users: "المستخدمون",
      guides: "المرشدون",
      places: "الأماكن",
      readyTrips: "الرحلات الجاهزة",
      customTrips: "الرحلات المخصصة",
      revenue: "الإيرادات",
      recentBookings: "أحدث الحجوزات",
      pendingGuides: "مرشدون بانتظار الموافقة",
      trip: "الرحلة",
      guide: "المرشد",
      amount: "المبلغ",
      status: "الحالة",
      unassigned: "غير مخصص",
      noBookings: "لا توجد حجوزات.",
      noPendingGuides: "لا يوجد مرشدون بانتظار الموافقة.",
    },
  },
};

const LanguageContext = createContext(null);

function getNested(value, path) {
  return path.split(".").reduce((acc, key) => (acc == null ? acc : acc[key]), value);
}

function interpolate(text, vars) {
  if (typeof text !== "string" || !vars) return text;
  return text.replace(/{{\s*(\w+)\s*}}/g, (_, key) =>
    vars[key] === undefined ? "" : String(vars[key])
  );
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
    return stored === "ar" ? "ar" : "en";
  });

  const setLanguage = (nextLanguage) => {
    setLanguageState(nextLanguage === "ar" ? "ar" : "en");
  };

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = RTL_LANGUAGES.has(language) ? "rtl" : "ltr";

    const meta = TRANSLATIONS[language].meta;
    document.title = meta.title;

    let descriptionTag = document.querySelector('meta[name="description"]');
    if (!descriptionTag) {
      descriptionTag = document.createElement("meta");
      descriptionTag.name = "description";
      document.head.appendChild(descriptionTag);
    }
    descriptionTag.setAttribute("content", meta.description);
  }, [language]);

  const value = useMemo(() => {
    const current = TRANSLATIONS[language];
    const fallback = TRANSLATIONS.en;

    const t = (key, vars) => {
      const raw = getNested(current, key) ?? getNested(fallback, key) ?? key;
      return interpolate(raw, vars);
    };

    return {
      language,
      isRTL: RTL_LANGUAGES.has(language),
      setLanguage,
      t,
      translations: current,
      supportedLanguages: [
        { code: "en", label: current.common.english },
        { code: "ar", label: current.common.arabic },
      ],
    };
  }, [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
